package template;

import model.report.Report;

import javax.swing.*;
import java.awt.*;
import java.awt.print.*;
import java.time.format.DateTimeFormatter;

/**
 * Exports a Report as a PDF-style printable document using Java's built-in
 * printing API (java.awt.print). No external library required.
 * The content is built incrementally across the four template steps and then
 * rendered to the printer/PDF writer in save().
 */
public class PDFExport extends ExportTemplate {

    private static final DateTimeFormatter FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    // Lines accumulated across the four template steps
    private final java.util.List<String> lines = new java.util.ArrayList<>();

    @Override
    protected void prepareHeader(Report report) {
        lines.clear();
        lines.add("===================================");
        lines.add("  BudgetBuddy Report - " + report.getReportType());
        lines.add("===================================");
        lines.add("Period    : " + report.getPeriod());
        lines.add("Generated : " + (report.getGeneratedAt() != null
                ? report.getGeneratedAt().format(FMT) : "N/A"));
        lines.add("");
    }

    @Override
    protected void writeBody(Report report) {
        lines.add("-----------------------------------");
        lines.add(String.format("%-20s %12s", "Total Income",
                String.format("$%.2f", report.getTotalIncome())));
        lines.add(String.format("%-20s %12s", "Total Expense",
                String.format("$%.2f", report.getTotalExpense())));
        lines.add(String.format("%-20s %12s", "Net Savings",
                String.format("$%.2f", report.getNetSavings())));
        lines.add("-----------------------------------");
        lines.add("");
    }

    @Override
    protected void formatFooter(Report report) {
        lines.add("Generated by BudgetBuddy");
        if (report.getGeneratedAt() != null) {
            lines.add(report.getGeneratedAt().format(FMT));
        }
    }

    @Override
    protected void save(Report report, String filePath) {
        // Use Java's PrinterJob to send the content to a PDF printer / print dialog
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("BudgetBuddy_Report_" + report.getReportType());

        job.setPrintable((graphics, pageFormat, pageIndex) -> {
            if (pageIndex > 0) return Printable.NO_SUCH_PAGE;

            Graphics2D g2 = (Graphics2D) graphics;
            g2.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 12));
            FontMetrics fm = g2.getFontMetrics();
            int lineHeight = fm.getHeight();

            int x = (int) pageFormat.getImageableX() + 10;
            int y = (int) pageFormat.getImageableY() + lineHeight;

            for (String line : lines) {
                g2.drawString(line, x, y);
                y += lineHeight;
            }
            return Printable.PAGE_EXISTS;
        });

        // Show print dialog so the user can choose "Save as PDF" or a printer
        if (job.printDialog()) {
            try {
                job.print();
                JOptionPane.showMessageDialog(null,
                        "Report sent to printer / PDF writer successfully.",
                        "Export PDF", JOptionPane.INFORMATION_MESSAGE);
            } catch (PrinterException e) {
                JOptionPane.showMessageDialog(null,
                        "PDF export failed: " + e.getMessage(),
                        "Export Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
}
